package models

import (
	"database/sql/driver"
	"errors"
	"fmt"
	"github.com/goccy/go-json"
	"gorm.io/gorm"
)

const (
	// CategoryTranslatePrefix 分类翻译前缀
	CategoryTranslatePrefix = "categoryName_%s"

	// Category Types
	CategoryTypeCommodity int8 = 1 // 商品分类

	// Category Status
	CategoryStatusDisabled int8 = -1 // 禁用
	CategoryStatusEnabled  int8 = 10 // 启用
)

// Category 商品分类表
type Category struct {
	BaseModel
	ParentID uint         `gorm:"type:int unsigned not null;index;comment:父级ID" json:"parentId"`
	AdminID  uint         `gorm:"type:int unsigned not null;uniqueIndex:idx_admin_symbol;comment:管理ID" json:"adminId"`
	Symbol   string       `gorm:"type:varchar(60) not null;uniqueIndex:idx_admin_symbol;comment:标识" json:"symbol"`
	Type     int8         `gorm:"type:tinyint not null;default:1;index;comment:类型(1:商品类型)" json:"type"`
	Name     string       `gorm:"type:varchar(60) not null;index;comment:名称" json:"name"`
	Icon     string       `gorm:"type:varchar(255);comment:图标" json:"icon"`
	Sort     int16        `gorm:"type:smallint not null;default:99;index;comment:排序" json:"sort"`
	Status   int8         `gorm:"type:tinyint not null;default:10;index;comment:状态(-1:禁用,10:启用)" json:"status"`
	Desc     string       `gorm:"type:text;comment:描述" json:"desc"`
	Data     CategoryData `gorm:"type:json;comment:数据" json:"data"`
}

// CategoryDisplayData 分类显示数据
type CategoryDisplayData struct {
	ID       uint                   `json:"id"`
	AdminID  uint                   `json:"adminId"`
	Symbol   string                 `json:"symbol"`
	Type     int8                   `json:"type"`
	Name     string                 `json:"name"`
	Icon     string                 `json:"icon"`
	Data     CategoryData           `json:"data"`
	Desc     string                 `json:"desc"`
	Children []*CategoryDisplayData `json:"children"`
}

// CategoryData 分类附加数据
type CategoryData struct{}

// Value implements the driver.Valuer interface
func (d CategoryData) Value() (driver.Value, error) {
	return json.Marshal(d)
}

// Scan implements the sql.Scanner interface
func (d *CategoryData) Scan(value interface{}) error {
	bytes, ok := value.([]byte)
	if !ok {
		return errors.New("type assertion to []byte failed")
	}

	return json.Unmarshal(bytes, &d)
}

//func init() {
//	// Create the table if it doesn't exist
//	if err := db.AutoMigrate(&Category{}); err != nil {
//		panic("Failed to auto migrate Category table: " + err.Error())
//	}
//
//	// Initialize system menus
//	if err := InitProductCategorys(db); err != nil {
//		panic("Failed to initialize product categorys: " + err.Error())
//	}
//}

// InitProductCategorys 初始化分类
func InitProductCategorys(db *gorm.DB) error {
	// Check if the table is empty
	var count int64
	db.Model(&Category{}).Count(&count)
	// If the table is empty, add initial data

	if count == 0 {
		categors := initCategorys()
		for _, v := range categors {
			v.Name = fmt.Sprintf(CategoryTranslatePrefix, v.Symbol)
		}
		return db.CreateInBatches(categors, len(categors)).Error
	}
	return nil
}

func initCategorys() []*Category {
	return []*Category{
		{
			BaseModel: BaseModel{ID: 1},
			AdminID:   SuperAdminID,
			Type:      CategoryTypeCommodity,
			Name:      "女装与时尚",
			Symbol:    "womenWearAndFashion",
			Icon:      "/commodity/category/womenFashion.png",
			Data:      CategoryData{},
		},
		{
			BaseModel: BaseModel{ID: 2},
			AdminID:   SuperAdminID,
			Type:      CategoryTypeCommodity,
			Name:      "女装",
			Symbol:    "womenWear",
			Icon:      "",
			Data:      CategoryData{},
			ParentID:  1,
		},
		{
			BaseModel: BaseModel{ID: 3},
			AdminID:   SuperAdminID,
			Type:      CategoryTypeCommodity,
			Name:      "裙子",
			Symbol:    "dress",
			Icon:      "/commodity/category/dress.jpg",
			Data:      CategoryData{},
			ParentID:  2,
		},
		{
			BaseModel: BaseModel{ID: 4},
			AdminID:   SuperAdminID,
			Type:      CategoryTypeCommodity,
			Name:      "女士T恤",
			Symbol:    "womenTShirt",
			Icon:      "/commodity/category/womenTShirt.jpg",
			Data:      CategoryData{},
			ParentID:  2,
		},
		{
			BaseModel: BaseModel{ID: 5},
			AdminID:   SuperAdminID,
			Type:      CategoryTypeCommodity,
			Name:      "女士衬衫",
			Symbol:    "womenShirt",
			Icon:      "/commodity/category/womenShirt.jpg",
			Data:      CategoryData{},
			ParentID:  2,
		},
		{
			BaseModel: BaseModel{ID: 6},
			AdminID:   SuperAdminID,
			Type:      CategoryTypeCommodity,
			Name:      "外套",
			Symbol:    "coat",
			Icon:      "/commodity/category/coat.jpg",
			Data:      CategoryData{},
			ParentID:  2,
		},
		{
			BaseModel: BaseModel{ID: 7},
			AdminID:   SuperAdminID,
			Type:      CategoryTypeCommodity,
			Name:      "女士牛仔裤",
			Symbol:    "womenJeans",
			Icon:      "/commodity/category/womenJeans.jpg",
			Data:      CategoryData{},
			ParentID:  2,
		},
		{
			BaseModel: BaseModel{ID: 8},
			AdminID:   SuperAdminID,
			Type:      CategoryTypeCommodity,
			Name:      "女士配件",
			Symbol:    "womenAccessories",
			Icon:      "",
			Data:      CategoryData{},
			ParentID:  1,
		},
		{
			BaseModel: BaseModel{ID: 9},
			AdminID:   SuperAdminID,
			Type:      CategoryTypeCommodity,
			Name:      "女士帽子",
			Symbol:    "womenHat",
			Icon:      "/commodity/category/womenHat.jpg",
			Data:      CategoryData{},
			ParentID:  8,
		},
		{
			BaseModel: BaseModel{ID: 10},
			AdminID:   SuperAdminID,
			Type:      CategoryTypeCommodity,
			Name:      "女士围巾",
			Symbol:    "womenScarf",
			Icon:      "/commodity/category/womenScarf.jpg",
			Data:      CategoryData{},
			ParentID:  8,
		},
		{
			BaseModel: BaseModel{ID: 11},
			AdminID:   SuperAdminID,
			Type:      CategoryTypeCommodity,
			Name:      "女士袜子",
			Symbol:    "womenSocks",
			Icon:      "/commodity/category/womenSocks.jpg",
			Data:      CategoryData{},
			ParentID:  8,
		},
		{
			BaseModel: BaseModel{ID: 20},
			AdminID:   SuperAdminID,
			Type:      CategoryTypeCommodity,
			Name:      "男装与时尚",
			Symbol:    "menWearAndFashion",
			Icon:      "/commodity/category/menFashion.png",
			Data:      CategoryData{},
		},
		{
			BaseModel: BaseModel{ID: 21},
			AdminID:   SuperAdminID,
			Type:      CategoryTypeCommodity,
			Name:      "男装",
			Symbol:    "menWear",
			Icon:      "",
			Data:      CategoryData{},
			ParentID:  20,
		},
		{
			BaseModel: BaseModel{ID: 22},
			AdminID:   SuperAdminID,
			Type:      CategoryTypeCommodity,
			Name:      "男士T恤",
			Symbol:    "menTShirt",
			Icon:      "/commodity/category/menTShirt.jpg",
			Data:      CategoryData{},
			ParentID:  21,
		},
		{
			BaseModel: BaseModel{ID: 23},
			AdminID:   SuperAdminID,
			Type:      CategoryTypeCommodity,
			Name:      "夹克",
			Symbol:    "jacket",
			Icon:      "/commodity/category/jacket.jpg",
			Data:      CategoryData{},
			ParentID:  21,
		},
		{
			BaseModel: BaseModel{ID: 24},
			AdminID:   SuperAdminID,
			Type:      CategoryTypeCommodity,
			Name:      "男士牛仔裤",
			Symbol:    "menJeans",
			Icon:      "/commodity/category/menJeans.jpg",
			Data:      CategoryData{},
			ParentID:  21,
		},
		{
			BaseModel: BaseModel{ID: 25},
			AdminID:   SuperAdminID,
			Type:      CategoryTypeCommodity,
			Name:      "男士衬衫",
			Symbol:    "menShirt",
			Icon:      "/commodity/category/menShirt.jpg",
			Data:      CategoryData{},
			ParentID:  21,
		},
		{
			BaseModel: BaseModel{ID: 26},
			AdminID:   SuperAdminID,
			Type:      CategoryTypeCommodity,
			Name:      "西装",
			Symbol:    "suit",
			Icon:      "/commodity/category/suit.jpg",
			Data:      CategoryData{},
			ParentID:  21,
		},
		{
			BaseModel: BaseModel{ID: 27},
			AdminID:   SuperAdminID,
			Type:      CategoryTypeCommodity,
			Name:      "男士配件",
			Symbol:    "menAccessories",
			Icon:      "",
			Data:      CategoryData{},
			ParentID:  20,
		},
		{
			BaseModel: BaseModel{ID: 28},
			AdminID:   SuperAdminID,
			Type:      CategoryTypeCommodity,
			Name:      "男士帽子",
			Symbol:    "menHat",
			Icon:      "/commodity/category/menHat.jpg",
			Data:      CategoryData{},
			ParentID:  27,
		},
		{
			BaseModel: BaseModel{ID: 29},
			AdminID:   SuperAdminID,
			Type:      CategoryTypeCommodity,
			Name:      "男士围巾",
			Symbol:    "menScarf",
			Icon:      "/commodity/category/menScarf.jpg",
			Data:      CategoryData{},
			ParentID:  27,
		},
		{
			BaseModel: BaseModel{ID: 30},
			AdminID:   SuperAdminID,
			Type:      CategoryTypeCommodity,
			Name:      "男士袜子",
			Symbol:    "menSocks",
			Icon:      "/commodity/category/menSocks.jpg",
			Data:      CategoryData{},
			ParentID:  27,
		},
		{
			BaseModel: BaseModel{ID: 40},
			AdminID:   SuperAdminID,
			Type:      CategoryTypeCommodity,
			Name:      "电脑与配件",
			Symbol:    "computersAndAccessories",
			Icon:      "/commodity/category/computersAccessories.png",
			Data:      CategoryData{},
		},
		{
			BaseModel: BaseModel{ID: 41},
			AdminID:   SuperAdminID,
			Type:      CategoryTypeCommodity,
			Name:      "台式机与一体机",
			Symbol:    "desktopAndAllInOne",
			Icon:      "",
			Data:      CategoryData{},
			ParentID:  40,
		},
		{
			BaseModel: BaseModel{ID: 42},
			AdminID:   SuperAdminID,
			Type:      CategoryTypeCommodity,
			Name:      "一体机",
			Symbol:    "allInOne",
			Icon:      "/commodity/category/allInOne.jpg",
			Data:      CategoryData{},
			ParentID:  41,
		},
		{
			BaseModel: BaseModel{ID: 43},
			AdminID:   SuperAdminID,
			Type:      CategoryTypeCommodity,
			Name:      "主机",
			Symbol:    "host",
			Icon:      "/commodity/category/host.jpg",
			Data:      CategoryData{},
			ParentID:  41,
		},
		{
			BaseModel: BaseModel{ID: 44},
			AdminID:   SuperAdminID,
			Type:      CategoryTypeCommodity,
			Name:      "台式整机",
			Symbol:    "desktopMachine",
			Icon:      "/commodity/category/desktopMachine.jpg",
			Data:      CategoryData{},
			ParentID:  41,
		},
		{
			BaseModel: BaseModel{ID: 45},
			AdminID:   SuperAdminID,
			Type:      CategoryTypeCommodity,
			Name:      "笔记本",
			Symbol:    "notebook",
			Icon:      "/commodity/category/notebook.jpg",
			Data:      CategoryData{},
			ParentID:  40,
		},
		{
			BaseModel: BaseModel{ID: 46},
			AdminID:   SuperAdminID,
			Type:      CategoryTypeCommodity,
			Name:      "鼠标",
			Symbol:    "mouse",
			Icon:      "/commodity/category/mouse.jpg",
			Data:      CategoryData{},
			ParentID:  40,
		},
		{
			BaseModel: BaseModel{ID: 47},
			AdminID:   SuperAdminID,
			Type:      CategoryTypeCommodity,
			Name:      "键盘",
			Symbol:    "keyboard",
			Icon:      "/commodity/category/keyboard.jpg",
			Data:      CategoryData{},
			ParentID:  40,
		},
		{
			BaseModel: BaseModel{ID: 48},
			AdminID:   SuperAdminID,
			Type:      CategoryTypeCommodity,
			Name:      "网络配置",
			Symbol:    "networkEquipment",
			Icon:      "",
			Data:      CategoryData{},
			ParentID:  40,
		},
		{
			BaseModel: BaseModel{ID: 49},
			AdminID:   SuperAdminID,
			Type:      CategoryTypeCommodity,
			Name:      "路由器",
			Symbol:    "router",
			Icon:      "/commodity/category/router.jpg",
			Data:      CategoryData{},
			ParentID:  48,
		},
		{
			BaseModel: BaseModel{ID: 50},
			AdminID:   SuperAdminID,
			Type:      CategoryTypeCommodity,
			Name:      "打印服务器",
			Symbol:    "printServer",
			Icon:      "/commodity/category/printServer.jpg",
			Data:      CategoryData{},
			ParentID:  48,
		},
		{
			BaseModel: BaseModel{ID: 51},
			AdminID:   SuperAdminID,
			Type:      CategoryTypeCommodity,
			Name:      "中继器",
			Symbol:    "concentrator",
			Icon:      "/commodity/category/concentrator.jpg",
			Data:      CategoryData{},
			ParentID:  48,
		},
		{
			BaseModel: BaseModel{ID: 60},
			AdminID:   SuperAdminID,
			Type:      CategoryTypeCommodity,
			Name:      "食品饮料",
			Symbol:    "foodAndBeverage",
			Icon:      "/commodity/category/foodAndBeverage.png",
			Data:      CategoryData{},
		},
		{
			BaseModel: BaseModel{ID: 61},
			AdminID:   SuperAdminID,
			Type:      CategoryTypeCommodity,
			Name:      "食品",
			Symbol:    "food",
			Icon:      "",
			Data:      CategoryData{},
			ParentID:  60,
		},
		{
			BaseModel: BaseModel{ID: 62},
			AdminID:   SuperAdminID,
			Type:      CategoryTypeCommodity,
			Name:      "糖果",
			Symbol:    "candies",
			Icon:      "/commodity/category/candies.jpg",
			Data:      CategoryData{},
			ParentID:  61,
		},
		{
			BaseModel: BaseModel{ID: 63},
			AdminID:   SuperAdminID,
			Type:      CategoryTypeCommodity,
			Name:      "果冻布丁",
			Symbol:    "jellyPudding",
			Icon:      "/commodity/category/jellyPudding.jpg",
			Data:      CategoryData{},
			ParentID:  61,
		},
		{
			BaseModel: BaseModel{ID: 64},
			AdminID:   SuperAdminID,
			Type:      CategoryTypeCommodity,
			Name:      "坚果炒货",
			Symbol:    "roastedNuts",
			Icon:      "/commodity/category/roastedNuts.jpg",
			Data:      CategoryData{},
			ParentID:  61,
		},
		{
			BaseModel: BaseModel{ID: 65},
			AdminID:   SuperAdminID,
			Type:      CategoryTypeCommodity,
			Name:      "肉类零食",
			Symbol:    "meatSnack",
			Icon:      "/commodity/category/meatSnack.jpg",
			Data:      CategoryData{},
			ParentID:  61,
		},
		{
			BaseModel: BaseModel{ID: 66},
			AdminID:   SuperAdminID,
			Type:      CategoryTypeCommodity,
			Name:      "膨化食品",
			Symbol:    "puffedFood",
			Icon:      "/commodity/category/puffedFood.jpg",
			Data:      CategoryData{},
			ParentID:  61,
		},
		{
			BaseModel: BaseModel{ID: 67},
			AdminID:   SuperAdminID,
			Type:      CategoryTypeCommodity,
			Name:      "果干蜜饯",
			Symbol:    "driedFruitPreserves",
			Icon:      "/commodity/category/driedFruitPreserves.jpg",
			Data:      CategoryData{},
			ParentID:  61,
		},
		{
			BaseModel: BaseModel{ID: 68},
			AdminID:   SuperAdminID,
			Type:      CategoryTypeCommodity,
			Name:      "酒水茶饮",
			Symbol:    "wineAndTea",
			Icon:      "",
			Data:      CategoryData{},
			ParentID:  60,
		},
		{
			BaseModel: BaseModel{ID: 69},
			AdminID:   SuperAdminID,
			Type:      CategoryTypeCommodity,
			Name:      "果茶",
			Symbol:    "nectar",
			Icon:      "/commodity/category/nectar.jpg",
			Data:      CategoryData{},
			ParentID:  68,
		},
		{
			BaseModel: BaseModel{ID: 70},
			AdminID:   SuperAdminID,
			Type:      CategoryTypeCommodity,
			Name:      "酒水",
			Symbol:    "wine",
			Icon:      "/commodity/category/wine.jpg",
			Data:      CategoryData{},
			ParentID:  68,
		},
		{
			BaseModel: BaseModel{ID: 71},
			AdminID:   SuperAdminID,
			Type:      CategoryTypeCommodity,
			Name:      "可乐",
			Symbol:    "cola",
			Icon:      "/commodity/category/cola.jpg",
			Data:      CategoryData{},
			ParentID:  68,
		},
		{
			BaseModel: BaseModel{ID: 80},
			AdminID:   SuperAdminID,
			Type:      CategoryTypeCommodity,
			Name:      "母婴玩具",
			Symbol:    "babyToy",
			Icon:      "/commodity/category/babyToy.png",
			Data:      CategoryData{},
		},
		{
			BaseModel: BaseModel{ID: 81},
			AdminID:   SuperAdminID,
			Type:      CategoryTypeCommodity,
			Name:      "婴幼玩具",
			Symbol:    "toddlersToy",
			Icon:      "",
			Data:      CategoryData{},
			ParentID:  80,
		},
		{
			BaseModel: BaseModel{ID: 82},
			AdminID:   SuperAdminID,
			Type:      CategoryTypeCommodity,
			Name:      "游戏垫",
			Symbol:    "playMat",
			Icon:      "/commodity/category/playMat.jpg",
			Data:      CategoryData{},
			ParentID:  81,
		},
		{
			BaseModel: BaseModel{ID: 83},
			AdminID:   SuperAdminID,
			Type:      CategoryTypeCommodity,
			Name:      "摇摇车",
			Symbol:    "kiddieRide",
			Icon:      "/commodity/category/kiddieRide.jpg",
			Data:      CategoryData{},
			ParentID:  81,
		},
		{
			BaseModel: BaseModel{ID: 84},
			AdminID:   SuperAdminID,
			Type:      CategoryTypeCommodity,
			Name:      "浴室玩具",
			Symbol:    "bathToy",
			Icon:      "/commodity/category/babyToy.jpg",
			Data:      CategoryData{},
			ParentID:  81,
		},
		{
			BaseModel: BaseModel{ID: 85},
			AdminID:   SuperAdminID,
			Type:      CategoryTypeCommodity,
			Name:      "敲击玩具",
			Symbol:    "percussionToy",
			Icon:      "/commodity/category/percussionToy.jpg",
			Data:      CategoryData{},
			ParentID:  81,
		},
		{
			BaseModel: BaseModel{ID: 86},
			AdminID:   SuperAdminID,
			Type:      CategoryTypeCommodity,
			Name:      "木马摇马",
			Symbol:    "rockingHorse",
			Icon:      "/commodity/category/rockingHorse.jpg",
			Data:      CategoryData{},
			ParentID:  81,
		},
		{
			BaseModel: BaseModel{ID: 87},
			AdminID:   SuperAdminID,
			Type:      CategoryTypeCommodity,
			Name:      "游戏屋",
			Symbol:    "playTent",
			Icon:      "/commodity/category/playTent.jpg",
			Data:      CategoryData{},
			ParentID:  81,
		},
		{
			BaseModel: BaseModel{ID: 88},
			AdminID:   SuperAdminID,
			Type:      CategoryTypeCommodity,
			Name:      "毛绒布艺",
			Symbol:    "plushFabric",
			Icon:      "",
			Data:      CategoryData{},
			ParentID:  80,
		},
		{
			BaseModel: BaseModel{ID: 89},
			AdminID:   SuperAdminID,
			Type:      CategoryTypeCommodity,
			Name:      "毛绒木偶",
			Symbol:    "plushPuppet",
			Icon:      "/commodity/category/plushPuppet.jpg",
			Data:      CategoryData{},
			ParentID:  88,
		},
		{
			BaseModel: BaseModel{ID: 90},
			AdminID:   SuperAdminID,
			Type:      CategoryTypeCommodity,
			Name:      "毛绒收纳",
			Symbol:    "plushStorage",
			Icon:      "/commodity/category/plushStorage.jpg",
			Data:      CategoryData{},
			ParentID:  88,
		},
		{
			BaseModel: BaseModel{ID: 91},
			AdminID:   SuperAdminID,
			Type:      CategoryTypeCommodity,
			Name:      "毛绒背包",
			Symbol:    "plushBackpack",
			Icon:      "/commodity/category/plushBackpack.jpg",
			Data:      CategoryData{},
			ParentID:  88,
		},
		{
			BaseModel: BaseModel{ID: 100},
			AdminID:   SuperAdminID,
			Type:      CategoryTypeCommodity,
			Name:      "运动及户外",
			Symbol:    "sportsAndOutdoor",
			Icon:      "/commodity/category/sportsAndOutdoor.jpeg",
			Data:      CategoryData{},
		},
		{
			BaseModel: BaseModel{ID: 101},
			AdminID:   SuperAdminID,
			Type:      CategoryTypeCommodity,
			Name:      "运动户外",
			Symbol:    "sportsOutdoors",
			Icon:      "",
			Data:      CategoryData{},
			ParentID:  100,
		},
		{
			BaseModel: BaseModel{ID: 102},
			AdminID:   SuperAdminID,
			Type:      CategoryTypeCommodity,
			Name:      "冲浪服",
			Symbol:    "surfingWetsuit",
			Icon:      "/commodity/category/surfingWetsuit.jpg",
			Data:      CategoryData{},
			ParentID:  101,
		},
		{
			BaseModel: BaseModel{ID: 103},
			AdminID:   SuperAdminID,
			Type:      CategoryTypeCommodity,
			Name:      "篮球服",
			Symbol:    "basketballClothes",
			Icon:      "/commodity/category/basketballClothes.jpg",
			Data:      CategoryData{},
			ParentID:  101,
		},
		{
			BaseModel: BaseModel{ID: 104},
			AdminID:   SuperAdminID,
			Type:      CategoryTypeCommodity,
			Name:      "瑜伽服",
			Symbol:    "yogaClothes",
			Icon:      "/commodity/category/yogaClothes.jpg",
			Data:      CategoryData{},
			ParentID:  101,
		},
		{
			BaseModel: BaseModel{ID: 105},
			AdminID:   SuperAdminID,
			Type:      CategoryTypeCommodity,
			Name:      "登山鞋",
			Symbol:    "climbingBoot",
			Icon:      "/commodity/category/climbingBoot.jpg",
			Data:      CategoryData{},
			ParentID:  101,
		},
		{
			BaseModel: BaseModel{ID: 106},
			AdminID:   SuperAdminID,
			Type:      CategoryTypeCommodity,
			Name:      "登山杖",
			Symbol:    "alpenstock",
			Icon:      "/commodity/category/alpenstock.jpg",
			Data:      CategoryData{},
			ParentID:  101,
		},
		{
			BaseModel: BaseModel{ID: 107},
			AdminID:   SuperAdminID,
			Type:      CategoryTypeCommodity,
			Name:      "户外运动包",
			Symbol:    "outdoorSportsBag",
			Icon:      "",
			Data:      CategoryData{},
			ParentID:  100,
		},
		{
			BaseModel: BaseModel{ID: 108},
			AdminID:   SuperAdminID,
			Type:      CategoryTypeCommodity,
			Name:      "登山包",
			Symbol:    "campingBag",
			Icon:      "/commodity/category/campingBag.jpg",
			Data:      CategoryData{},
			ParentID:  107,
		},
		{
			BaseModel: BaseModel{ID: 109},
			AdminID:   SuperAdminID,
			Type:      CategoryTypeCommodity,
			Name:      "健身包",
			Symbol:    "gymBag",
			Icon:      "/commodity/category/gymBag.jpg",
			Data:      CategoryData{},
			ParentID:  107,
		},
		{
			BaseModel: BaseModel{ID: 110},
			AdminID:   SuperAdminID,
			Type:      CategoryTypeCommodity,
			Name:      "装备包",
			Symbol:    "equipmentPack",
			Icon:      "/commodity/category/equipmentPack.jpg",
			Data:      CategoryData{},
			ParentID:  107,
		},
		{
			BaseModel: BaseModel{ID: 112},
			AdminID:   SuperAdminID,
			Type:      CategoryTypeCommodity,
			Name:      "护具",
			Symbol:    "protectiveClothing",
			Icon:      "/commodity/category/protectiveClothing.jpg",
			Data:      CategoryData{},
			ParentID:  101,
		},
		{
			BaseModel: BaseModel{ID: 113},
			AdminID:   SuperAdminID,
			Type:      CategoryTypeCommodity,
			Name:      "电子设备",
			Symbol:    "electronicEquipment",
			Icon:      "/commodity/category/electronicEquipment.jpg",
			Data:      CategoryData{},
			ParentID:  101,
		},
		{
			BaseModel: BaseModel{ID: 120},
			AdminID:   SuperAdminID,
			Type:      CategoryTypeCommodity,
			Name:      "家居生活",
			Symbol:    "homeLife",
			Icon:      "/commodity/category/homeLife.png",
			Data:      CategoryData{},
		},
		{
			BaseModel: BaseModel{ID: 121},
			AdminID:   SuperAdminID,
			Type:      CategoryTypeCommodity,
			Name:      "床上用品",
			Symbol:    "beddings",
			Icon:      "",
			Data:      CategoryData{},
			ParentID:  120,
		},
		{
			BaseModel: BaseModel{ID: 122},
			AdminID:   SuperAdminID,
			Type:      CategoryTypeCommodity,
			Name:      "枕头枕芯",
			Symbol:    "pillowCore",
			Icon:      "/commodity/category/pillowCore.jpg",
			Data:      CategoryData{},
			ParentID:  121,
		},
		{
			BaseModel: BaseModel{ID: 123},
			AdminID:   SuperAdminID,
			Type:      CategoryTypeCommodity,
			Name:      "被子",
			Symbol:    "quilt",
			Icon:      "/commodity/category/quilt.jpg",
			Data:      CategoryData{},
			ParentID:  121,
		},
		{
			BaseModel: BaseModel{ID: 124},
			AdminID:   SuperAdminID,
			Type:      CategoryTypeCommodity,
			Name:      "床垫",
			Symbol:    "mattress",
			Icon:      "/commodity/category/mattress.jpg",
			Data:      CategoryData{},
			ParentID:  121,
		},
		{
			BaseModel: BaseModel{ID: 125},
			AdminID:   SuperAdminID,
			Type:      CategoryTypeCommodity,
			Name:      "四件套",
			Symbol:    "fourPieceSet",
			Icon:      "/commodity/category/fourPieceSet.jpg",
			Data:      CategoryData{},
			ParentID:  121,
		},
		{
			BaseModel: BaseModel{ID: 126},
			AdminID:   SuperAdminID,
			Type:      CategoryTypeCommodity,
			Name:      "生活用品",
			Symbol:    "articlesOfDailyUse",
			Icon:      "",
			Data:      CategoryData{},
			ParentID:  120,
		},
		{
			BaseModel: BaseModel{ID: 127},
			AdminID:   SuperAdminID,
			Type:      CategoryTypeCommodity,
			Name:      "毛巾浴巾",
			Symbol:    "towelBath",
			Icon:      "/commodity/category/towelBath.jpg",
			Data:      CategoryData{},
			ParentID:  126,
		},
		{
			BaseModel: BaseModel{ID: 128},
			AdminID:   SuperAdminID,
			Type:      CategoryTypeCommodity,
			Name:      "拖鞋",
			Symbol:    "slipper",
			Icon:      "/commodity/category/slipper.jpg",
			Data:      CategoryData{},
			ParentID:  126,
		},
		{
			BaseModel: BaseModel{ID: 129},
			AdminID:   SuperAdminID,
			Type:      CategoryTypeCommodity,
			Name:      "马桶刷",
			Symbol:    "toiletBrush",
			Icon:      "/commodity/category/toiletBrush.jpg",
			Data:      CategoryData{},
			ParentID:  126,
		},
		{
			BaseModel: BaseModel{ID: 130},
			AdminID:   SuperAdminID,
			Type:      CategoryTypeCommodity,
			Name:      "珠宝及手表",
			Symbol:    "jeweleryAndWatches",
			Icon:      "/commodity/category/jeweleryAndWatches.png",
			Data:      CategoryData{},
		},
		{
			BaseModel: BaseModel{ID: 131},
			AdminID:   SuperAdminID,
			Type:      CategoryTypeCommodity,
			Name:      "女士珠宝饰品",
			Symbol:    "womenJeweleryAccessories",
			Icon:      "",
			Data:      CategoryData{},
			ParentID:  130,
		},
		{
			BaseModel: BaseModel{ID: 132},
			AdminID:   SuperAdminID,
			Type:      CategoryTypeCommodity,
			Name:      "戒指",
			Symbol:    "ring",
			Icon:      "/commodity/category/ring.jpg",
			Data:      CategoryData{},
			ParentID:  131,
		},
		{
			BaseModel: BaseModel{ID: 133},
			AdminID:   SuperAdminID,
			Type:      CategoryTypeCommodity,
			Name:      "手链",
			Symbol:    "bracelet",
			Icon:      "/commodity/category/bracelet.jpg",
			Data:      CategoryData{},
			ParentID:  131,
		},
		{
			BaseModel: BaseModel{ID: 134},
			AdminID:   SuperAdminID,
			Type:      CategoryTypeCommodity,
			Name:      "项链",
			Symbol:    "necklace",
			Icon:      "/commodity/category/necklace.jpg",
			Data:      CategoryData{},
			ParentID:  131,
		},
		{
			BaseModel: BaseModel{ID: 135},
			AdminID:   SuperAdminID,
			Type:      CategoryTypeCommodity,
			Name:      "发饰",
			Symbol:    "hairAccessory",
			Icon:      "/commodity/category/hairAccessory.jpg",
			Data:      CategoryData{},
			ParentID:  131,
		},
		{
			BaseModel: BaseModel{ID: 136},
			AdminID:   SuperAdminID,
			Type:      CategoryTypeCommodity,
			Name:      "珍珠饰品",
			Symbol:    "pearlAccessories",
			Icon:      "/commodity/category/pearlAccessories.jpg",
			Data:      CategoryData{},
			ParentID:  131,
		},
		{
			BaseModel: BaseModel{ID: 137},
			AdminID:   SuperAdminID,
			Type:      CategoryTypeCommodity,
			Name:      "耳饰",
			Symbol:    "earring",
			Icon:      "/commodity/category/earring.jpg",
			Data:      CategoryData{},
			ParentID:  131,
		},
		{
			BaseModel: BaseModel{ID: 138},
			AdminID:   SuperAdminID,
			Type:      CategoryTypeCommodity,
			Name:      "饰品配件",
			Symbol:    "jewelryAccessory",
			Icon:      "",
			Data:      CategoryData{},
			ParentID:  130,
		},
		{
			BaseModel: BaseModel{ID: 139},
			AdminID:   SuperAdminID,
			Type:      CategoryTypeCommodity,
			Name:      "首饰盒",
			Symbol:    "jewelCase",
			Icon:      "/commodity/category/jewelCase.jpg",
			Data:      CategoryData{},
			ParentID:  138,
		},
		{
			BaseModel: BaseModel{ID: 140},
			AdminID:   SuperAdminID,
			Type:      CategoryTypeCommodity,
			Name:      "饰品清洁",
			Symbol:    "jewelryCleaning",
			Icon:      "/commodity/category/jewelryCleaning.jpg",
			Data:      CategoryData{},
			ParentID:  138,
		},
		{
			BaseModel: BaseModel{ID: 141},
			AdminID:   SuperAdminID,
			Type:      CategoryTypeCommodity,
			Name:      "裸钻",
			Symbol:    "looseDiamond",
			Icon:      "/commodity/category/looseDiamond.jpg",
			Data:      CategoryData{},
			ParentID:  138,
		},
		{
			BaseModel: BaseModel{ID: 150},
			AdminID:   SuperAdminID,
			Type:      CategoryTypeCommodity,
			Name:      "手机数码",
			Symbol:    "mobilePhoneNumber",
			Icon:      "/commodity/category/mobileDigital.jpeg",
			Data:      CategoryData{},
		},
		{
			BaseModel: BaseModel{ID: 151},
			AdminID:   SuperAdminID,
			Type:      CategoryTypeCommodity,
			Name:      "手机通讯",
			Symbol:    "mobilePhoneCommunication",
			Icon:      "",
			Data:      CategoryData{},
			ParentID:  150,
		},
		{
			BaseModel: BaseModel{ID: 152},
			AdminID:   SuperAdminID,
			Type:      CategoryTypeCommodity,
			Name:      "手机",
			Symbol:    "cellPhone",
			Icon:      "/commodity/category/cellPhone.jpg",
			Data:      CategoryData{},
			ParentID:  151,
		},
		{
			BaseModel: BaseModel{ID: 153},
			AdminID:   SuperAdminID,
			Type:      CategoryTypeCommodity,
			Name:      "SIM卡工具",
			Symbol:    "simToolkit",
			Icon:      "/commodity/category/simToolkit.jpg",
			Data:      CategoryData{},
			ParentID:  151,
		},
		{
			BaseModel: BaseModel{ID: 154},
			AdminID:   SuperAdminID,
			Type:      CategoryTypeCommodity,
			Name:      "手机配件",
			Symbol:    "mobilePhoneSpareParts",
			Icon:      "",
			Data:      CategoryData{},
			ParentID:  150,
		},
		{
			BaseModel: BaseModel{ID: 155},
			AdminID:   SuperAdminID,
			Type:      CategoryTypeCommodity,
			Name:      "耳机",
			Symbol:    "earphone",
			Icon:      "/commodity/category/earphone.jpg",
			Data:      CategoryData{},
			ParentID:  154,
		},
		{
			BaseModel: BaseModel{ID: 156},
			AdminID:   SuperAdminID,
			Type:      CategoryTypeCommodity,
			Name:      "手机膜",
			Symbol:    "phoneScreenFilm",
			Icon:      "/commodity/category/phoneScreenFilm.jpg",
			Data:      CategoryData{},
			ParentID:  154,
		},
		{
			BaseModel: BaseModel{ID: 157},
			AdminID:   SuperAdminID,
			Type:      CategoryTypeCommodity,
			Name:      "自拍杆",
			Symbol:    "selfieStick",
			Icon:      "/commodity/category/selfieStick.jpg",
			Data:      CategoryData{},
			ParentID:  154,
		},
		{
			BaseModel: BaseModel{ID: 158},
			AdminID:   SuperAdminID,
			Type:      CategoryTypeCommodity,
			Name:      "手机壳",
			Symbol:    "protectiveContainment",
			Icon:      "/commodity/category/protectiveContainment.jpg",
			Data:      CategoryData{},
			ParentID:  154,
		},
		{
			BaseModel: BaseModel{ID: 159},
			AdminID:   SuperAdminID,
			Type:      CategoryTypeCommodity,
			Name:      "手机镜头",
			Symbol:    "mobilePhoneLens",
			Icon:      "/commodity/category/mobilePhoneLens.jpg",
			Data:      CategoryData{},
			ParentID:  154,
		},
		{
			BaseModel: BaseModel{ID: 160},
			AdminID:   SuperAdminID,
			Type:      CategoryTypeCommodity,
			Name:      "充电器",
			Symbol:    "charger",
			Icon:      "/commodity/category/charger.jpg",
			Data:      CategoryData{},
			ParentID:  154,
		},
		{
			BaseModel: BaseModel{ID: 170},
			AdminID:   SuperAdminID,
			Type:      CategoryTypeCommodity,
			Name:      "美容化妆",
			Symbol:    "cosmetics",
			Icon:      "/commodity/category/cosmetics.png",
			Data:      CategoryData{},
		},
		{
			BaseModel: BaseModel{ID: 171},
			AdminID:   SuperAdminID,
			Type:      CategoryTypeCommodity,
			Name:      "面部护肤",
			Symbol:    "facialSkinCare",
			Icon:      "",
			Data:      CategoryData{},
			ParentID:  170,
		},
		{
			BaseModel: BaseModel{ID: 172},
			AdminID:   SuperAdminID,
			Type:      CategoryTypeCommodity,
			Name:      "面膜",
			Symbol:    "facialMask",
			Icon:      "/commodity/category/facialMask.jpg",
			Data:      CategoryData{},
			ParentID:  171,
		},
		{
			BaseModel: BaseModel{ID: 173},
			AdminID:   SuperAdminID,
			Type:      CategoryTypeCommodity,
			Name:      "面霜乳液",
			Symbol:    "creamLotion",
			Icon:      "/commodity/category/creamLotion.jpg",
			Data:      CategoryData{},
			ParentID:  171,
		},
		{
			BaseModel: BaseModel{ID: 174},
			AdminID:   SuperAdminID,
			Type:      CategoryTypeCommodity,
			Name:      "精华",
			Symbol:    "essence",
			Icon:      "/commodity/category/essence.jpg",
			Data:      CategoryData{},
			ParentID:  171,
		},
		{
			BaseModel: BaseModel{ID: 175},
			AdminID:   SuperAdminID,
			Type:      CategoryTypeCommodity,
			Name:      "面部清洁",
			Symbol:    "facialCleansing",
			Icon:      "/commodity/category/facialCleansing.jpg",
			Data:      CategoryData{},
			ParentID:  171,
		},
		{
			BaseModel: BaseModel{ID: 176},
			AdminID:   SuperAdminID,
			Type:      CategoryTypeCommodity,
			Name:      "防晒霜",
			Symbol:    "sunCream",
			Icon:      "/commodity/category/sunCream.jpg",
			Data:      CategoryData{},
			ParentID:  171,
		},
		{
			BaseModel: BaseModel{ID: 177},
			AdminID:   SuperAdminID,
			Type:      CategoryTypeCommodity,
			Name:      "润唇膏",
			Symbol:    "lipPomade",
			Icon:      "/commodity/category/lipPomade.jpg",
			Data:      CategoryData{},
			ParentID:  171,
		},
		{
			BaseModel: BaseModel{ID: 178},
			AdminID:   SuperAdminID,
			Type:      CategoryTypeCommodity,
			Name:      "美发护肤",
			Symbol:    "hairAndSkinCare",
			Icon:      "",
			Data:      CategoryData{},
			ParentID:  170,
		},
		{
			BaseModel: BaseModel{ID: 179},
			AdminID:   SuperAdminID,
			Type:      CategoryTypeCommodity,
			Name:      "洗发",
			Symbol:    "liquidShampoo",
			Icon:      "/commodity/category/liquidShampoo.jpg",
			Data:      CategoryData{},
			ParentID:  178,
		},
		{
			BaseModel: BaseModel{ID: 180},
			AdminID:   SuperAdminID,
			Type:      CategoryTypeCommodity,
			Name:      "染发",
			Symbol:    "hairDyeLiquid",
			Icon:      "/commodity/category/hairDyeLiquid.jpg",
			Data:      CategoryData{},
			ParentID:  178,
		},
		{
			BaseModel: BaseModel{ID: 181},
			AdminID:   SuperAdminID,
			Type:      CategoryTypeCommodity,
			Name:      "护发",
			Symbol:    "hairConditioner",
			Icon:      "/commodity/category/hairConditioner.jpg",
			Data:      CategoryData{},
			ParentID:  178,
		},
		{
			BaseModel: BaseModel{ID: 182},
			AdminID:   SuperAdminID,
			Type:      CategoryTypeCommodity,
			Name:      "奢侈品",
			Symbol:    "luxury",
			Icon:      "/commodity/category/luxury.jpg",
			Data:      CategoryData{},
		},
		{
			BaseModel: BaseModel{ID: 183},
			AdminID:   SuperAdminID,
			Type:      CategoryTypeCommodity,
			Name:      "香奈儿",
			Symbol:    "chanel",
			Icon:      "/commodity/category/chanel.jpg",
			Data:      CategoryData{},
			ParentID:  182,
		},
		{
			BaseModel: BaseModel{ID: 184},
			AdminID:   SuperAdminID,
			Type:      CategoryTypeCommodity,
			Name:      "路易威登",
			Symbol:    "louisVuitton",
			Icon:      "/commodity/category/louisVuitton.jpg",
			Data:      CategoryData{},
			ParentID:  182,
		},
		{
			BaseModel: BaseModel{ID: 185},
			AdminID:   SuperAdminID,
			Type:      CategoryTypeCommodity,
			Name:      "古驰",
			Symbol:    "gucci",
			Icon:      "/commodity/category/gucci.jpg",
			Data:      CategoryData{},
			ParentID:  182,
		},
		{
			BaseModel: BaseModel{ID: 186},
			AdminID:   SuperAdminID,
			Type:      CategoryTypeCommodity,
			Name:      "普拉达",
			Symbol:    "prada",
			Icon:      "/commodity/category/prada.jpg",
			Data:      CategoryData{},
			ParentID:  182,
		},
		{
			BaseModel: BaseModel{ID: 187},
			AdminID:   SuperAdminID,
			Type:      CategoryTypeCommodity,
			Name:      "迪奥",
			Symbol:    "dior",
			Icon:      "/commodity/category/dior.jpg",
			Data:      CategoryData{},
			ParentID:  182,
		},
		{
			BaseModel: BaseModel{ID: 188},
			AdminID:   SuperAdminID,
			Type:      CategoryTypeCommodity,
			Name:      "博柏利",
			Symbol:    "burberry",
			Icon:      "/commodity/category/burberry.jpg",
			Data:      CategoryData{},
			ParentID:  182,
		},
		{
			BaseModel: BaseModel{ID: 189},
			AdminID:   SuperAdminID,
			Type:      CategoryTypeCommodity,
			Name:      "芬迪",
			Symbol:    "fendi",
			Icon:      "/commodity/category/fendi.jpg",
			Data:      CategoryData{},
			ParentID:  182,
		},
		{
			BaseModel: BaseModel{ID: 190},
			AdminID:   SuperAdminID,
			Type:      CategoryTypeCommodity,
			Name:      "巴黎世家",
			Symbol:    "balenciaga",
			Icon:      "/commodity/category/balenciaga.jpg",
			Data:      CategoryData{},
			ParentID:  182,
		},
		{
			BaseModel: BaseModel{ID: 191},
			AdminID:   SuperAdminID,
			Type:      CategoryTypeCommodity,
			Name:      "卡地亚",
			Symbol:    "cartier",
			Icon:      "/commodity/category/cartier.jpg",
			Data:      CategoryData{},
			ParentID:  182,
		},
		{
			BaseModel: BaseModel{ID: 192},
			AdminID:   SuperAdminID,
			Type:      CategoryTypeCommodity,
			Name:      "宝格丽",
			Symbol:    "bvlgari",
			Icon:      "/commodity/category/bvlgari.jpg",
			Data:      CategoryData{},
			ParentID:  182,
		},
		{
			BaseModel: BaseModel{ID: 193},
			AdminID:   SuperAdminID,
			Type:      CategoryTypeCommodity,
			Name:      "梵克雅宝",
			Symbol:    "vanCleefArpels",
			Icon:      "/commodity/category/vanCleefArpels.jpg",
			Data:      CategoryData{},
			ParentID:  182,
		},
	}
}
