// This file is generated by GoAdmin CLI adm.
package tables

import "github.com/GoAdminGroup/go-admin/plugins/admin/modules/table"

// Generators is a map of table models.
//
// The key of Generators is the prefix of table info url.
// The corresponding value is the Form and Table data.
//
// http://{{config.Domain}}:{{Port}}/{{config.Prefix}}/info/{{key}}
//
// example:
//
// "client" => http://localhost:9033/admin/info/client
// "port" => http://localhost:9033/admin/info/port
//
// example end
var Generators = map[string]table.Generator{
	"test":         GetTestTable,
	"system_files": GetSystemFileTable,
	// generators end
}
